repos:
  - repo: https://github.com/keep-network/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: lint-js
        name: "lint js"
        entry: /usr/bin/env bash -c "npm run lint:js"
        files: '\.js$'
        language: script
        description: "Checks JS code according to the package's linter configuration"
      - id: lint-sol
        name: "lint solidity"
        entry: /usr/bin/env bash -c "npm run lint:sol"
        files: '\.sol$'
        language: script
        description: "Checks Solidity code according to the package's linter configuration"
      - id: prettier
        name: "prettier"
        entry: /usr/bin/env bash -c "npx prettier --check ."
        language: script
        description: "Checks code according to the package's formatting configuration"
