repos:
  - repo: https://github.com/keep-network/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: root-format
        name: "Check root directory code formatting"
        entry: /usr/bin/env bash -c "yarn format"
        exclude: '^solidity\/|^yearn\/|^typescript\/|^monitoring\/'
        language: script
        description: "Checks root directory code according to the formatting configuration"
      - id: solidity-format
        name: "Check solidity directory code formatting"
        entry: /usr/bin/env bash -c "cd solidity && yarn format"
        files: "^solidity/"
        language: script
        description: "Checks solidity directory code according to the formatting configuration"
      - id: yearn-format
        name: "Check yearn directory code formatting"
        entry: /usr/bin/env bash -c "cd yearn && yarn format"
        files: "^yearn/"
        language: script
        description: "Checks yearn directory code according to the formatting configuration"
      - id: typescript-format
        name: "Check typescript directory code formatting"
        entry: /usr/bin/env bash -c "cd typescript && yarn format"
        files: "^typescript/"
        language: script
        description: "Checks typescript directory code according to the formatting configuration"
      - id: monitoring-format
        name: "Check monitoring directory code formatting"
        entry: /usr/bin/env bash -c "cd monitoring && yarn format"
        files: "^monitoring/"
        language: script
        description: "Checks monitoring directory code according to the formatting configuration"
